### ISSUE TITLE
[RediSearch] Why is it just experimental?

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#131]
I was very hyped when I did begin this project to see that `Redis` has a SearchModule because I think it would be a great lightweight alternative also to Elasticsearch / Opensearch and so on.

While working on the implementation of the RediSearch we did go with JSON Documents as this is the most common usage of it on our side. So we are using JSON and Search module to store our documents. 

So where are the problems. Let see we want to index a document like this:

```json
{
    "uuid": "3d3586fe-0416-4572-8ce1-c7b6b9e424ff",
    "title": "Hello World - And other Foo Bar things",
    "tag": "some-tag",
    "description": "A simple description about the article which is searchable."
}
```

For this documents we create the following Schema:

```redis
FT.CREATE news ON JSON PREFIX 1 news SCHEMA $.uuid AS uuid TEXT SORTABLE $.title AS title TEXT $.description AS description TEXT $.tag AS tag TEXT SORTABLE
```

To write this JSON into our Redis we are using the following code:

```redis
JSON.SET news:3d3586fe-0416-4572-8ce1-c7b6b9e424ff $ '{"uuid": "3d3586fe-0416-4572-8ce1-c7b6b9e424ff","title": "Hello World - And other Foo Bar things","tag": "some-tag","description": "A simple description about the article which is searchable."}'
```

Now as example we want to create a filter on tag or another text field uuid. Here it comes complicated. RediSearch at current state different DIALECTs. If you read over it mostly the created new dialect to provide backward compatibility and still fixing some issues. We decided to go with DIALECT 3 so we are now quering the data:

```redis
FT.SEARCH news @uuid:(3d3586fe-0416-4572-8ce1-c7b6b9e424ff) DIALECT 3
FT.SEARCH news @tag:(some-tag) DIALECT 3
```

No result. Strange. Okay `-` is a special symbol we need to query the data: 

```redis
FT.SEARCH news @uuid:(3d3586fe\-0416\-4572\-8ce1\-c7b6b9e424ff) DIALECT 3
FT.SEARCH news @tag:(some\-tag) DIALECT 3
```

Still no result. So now we remove the document and index it without the `-` in the tag:

```redis
JSON.SET news:3d3586fe-0416-4572-8ce1-c7b6b9e424ff $ '{"uuid": "3d3586fe-0416-4572-8ce1-c7b6b9e424ff","title": "Hello World - And other Foo Bar things","tag": "sometag","description": "A simple description about the article which is searchable."}'
```

And then search again:

```redis
FT.SEARCH news @tag:(sometag) DIALECT 3
```

And we got now a result. But we manipulated our index data which we didn't want todo as that should contain the `-` in it and should be returned.

So some reasearch later Redis solution for this problem which is in our case not not usable for us is to escape the value when creating the JSON Document. Yes you read correctly we would need to manipulate our json document which is valid and can be read and write correctly that it works with the `-`. So lets write a document with:

```redis
JSON.SET news:3d3586fe-0416-4572-8ce1-c7b6b9e424ff $ '{"uuid": "3d3586fe\\-0416\\-4572\\-8ce1\\-c7b6b9e424ff","title": "Hello World - And other Foo Bar things","tag": "some\\-tag","description": "A simple description about the article which is searchable."}'
```

```redis
FT.SEARCH news @uuid:(3d3586fe\-0416\-4572\-8ce1\-c7b6b9e424ff) DIALECT 3
FT.SEARCH news @tag:(some\-tag) DIALECT 3
```

This works but is for us not acceptable solution as reading the document this way:

```redis
JSON.GET news:3d3586fe-0416-4572-8ce1-c7b6b9e424ff
```

Will us return the JSON with `\` before the `-`.

Why the RediSearch would have been a lot of potential this kind of little issue make it sadly not very usable. As `filters` are common usecase for `searches` this kind of queries should work without getting strange manipulated JSON back. What the problem is also with `\\` as it is not easily can be added to the JSON as a `key` could also have a `-` which ends in endless escaping and converting data on all ends.  We also tried to use `TAG` instead of `TEXT` type for the field which was mention in some comment but it also did not work there liked expected and ended in the same issue. This is way as current state I can only mark RediSearch `@experimental` which maybe will end up that we even remove the adapter in the future.

Here the open releated issues on RediSearch repository:

 - https://github.com/RediSearch/RediSearch/issues/1304
 - https://github.com/RediSearch/RediSearch/issues/1148
 
If somebody knows a solution on the Schema side share it with us so we can fix that issue.

**Comment by alexander-schranz** [comment]
After some feedback from @redis and the help of @oshadmi  (Thank you!) https://github.com/RediSearch/RediSearch/issues/1304. I could find a working workaround for this issue. The first step is if a Field is `filterable` we create additional `.raw` field e.g.:

```diff
{
    "uuid": "3d3586fe-0416-4572-8ce1-c7b6b9e424ff",
    "title": "Hello World - And other Foo Bar things",
+   "tags.raw": ["some-tag"],
    "tags": ["some-tag"]
}
```

The `.raw` fields and the `identifier` are by default `.raw` are from type `TAG`. There is something special about tags and why I thought they also don't work. Because the need to be queried differently then text fields with `{}` instead of `()`. This looks like:

```diff
-@uuid{3d3586fe\-0416\-4572\-8ce1\-c7b6b9e424ff}
+@uuid(3d3586fe\-0416\-4572\-8ce1\-c7b6b9e424ff)
```

The schema of the `tags.raw` we need to escape `.` this can be achieved in the JSON pointer via:

```diff
-$.tags.raw
+$['tags.raw'][*]
```

So at the end our SCHMEMA looks like this:

```bash
FT.CREATE test_complex ON JSON PREFIX 1 test_complex SCHEMA "$['uuid']" AS uuid TAG SORTABLE "$['title']" AS title TEXT "$['article']" AS article TEXT "$['blocks']['text'][*]['title']" AS blocks__text__title TEXT "$['blocks']['text'][*]['description']" AS blocks__text__description TEXT "$['blocks']['embed'][*]['title']" AS blocks__embed__title TEXT "$['footer']['title']" AS footertitle TEXT "$['created.raw']" AS created__raw TAG SORTABLE "$['commentsCount']" AS commentsCount NUMERIC SORTABLE "$['rating']" AS rating NUMERIC SORTABLE "$['comments'][*]['text']" AS commentstext TEXT "$['tags'][*]" AS tags TEXT "$['tags.raw'][*]" AS tags__raw TAG "$['categoryIds'][*]" AS categoryIds NUMERIC
```

Important part here is that additional tags `.raw` field:

```diff
 "$['tags'][*]" AS tags TEXT
+"$['tags.raw'][*]" AS tags__raw
```

Our document like this:

```bash
JSON.SET test_complex:23b30f01-d8fd-4dca-b36a-4710e360a965 $ '{"uuid":"23b30f01-d8fd-4dca-b36a-4710e360a965","title":"New Blog","header":{"image":{"media":1}},"article":"<article><h2>New Subtitle<\/h2><p>A html field with some content<\/p><\/article>","blocks":{"text":[{"_originalIndex":0,"title":"Titel","description":"<p>Description<\/p>","media":[3,4]},{"_originalIndex":1,"title":"Titel 2"},{"_originalIndex":3,"title":"Titel 4","description":"<p>Description 4<\/p>","media":[3,4]}],"embed":[{"_originalIndex":2,"title":"Video","media":"https:\/\/www.youtube.com\/watch?v=iYM2zFP3Zn0"}]},"footer":{"title":"New Footer"},"created":"2022-01-24T12:00:00+01:00","commentsCount":2,"rating":3.5,"comments":[{"email":"admin.nonesearchablefield@localhost","text":"Awesome blog!"},{"email":"example.nonesearchablefield@localhost","text":"Like this blog!"}],"tags":["Tech","UI"],"tags.raw":["Tech","UI"],"categoryIds":[1,2]}'
```

And we can filter values like this via uuid tag field and the tags__raw field:

```bash
FT.SEARCH test_complex @uuid:{23b30f01\-d8fd\-4dca\-b36a\-4710e360a965} DIALECT 2
FT.SEARCH test_complex @tags__raw:{UI} DIALECT 3
```

**Comment by rowantrollope** [comment]
Thanks Alexander. I've had the same experience. We will prioritize fixing it

**Comment by K-Jo** [comment]
@alexander-schranz thanks for the feedback.  

One small thing, unless you change the data in the raw fields of the document there is no need to duplicate the data

`"$['tags'][*]" AS tags TEXT "$['tags.raw'][*]" AS tags__raw TAG`
works as well as
`"$['tags'][*]" AS tags TEXT "$['tags'][*]" AS tags__raw TAG`

**Comment by alexander-schranz** [comment]
@K-Jo yeah that is true, one of the advantages of redisearch using JSON pointers for the mappings.
