### ISSUE TITLE
[Docs] Clarification of terminology in the "Getting Started" section of the documentation is missing

### ISSUE THREAD

**Issue by froschdesign** [schranz-search/schranz-search#154]
The ["Getting Started" section](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst) of the documentation uses terms that are not described, but the entire section is based on this terminology:

- Schema
- Engine
- Search Engine
- Indexes
- Documents

The terms are used in the headlines and content:

- [Configure Schema](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#configure-schema)
- [Configure Engine](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#configure-schema)
- [Prepare Search Engine](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#prepare-search-engine)
- [Create Indexes](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#create-indexes)
- [Add Documents](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#add-documents)
- [Search Documents](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#search-documents)
- [Filter Documents](https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#filter-documents)

Additionally, the use of "engine" and "search engine" without explanation is very confusing or even unclear.

--- 

One description can be found: 

> The `Engine` is the main class which will be used to communicate with the search engine.

Therefore, I suggest adding a list of terms with descriptions at the top of the page.

**Comment by alexander-schranz** [comment]
@froschdesign  Thx for the feedback. Maybe it was not a good choice to name that class `Engine` 🤔, but did not come up with a better name yet.

Beside describing the terms also, do you think it would avoid confusion if we use instead of `Search engines` the terms `Search services`, or what other word could use here to not use Engine here also 🤔 .

**Comment by alexander-schranz** [comment]
I added a glossary to the first page of the docs to make things more clear as part of the diagram and structure docs: https://schranz-search.github.io/schranz-search/
