### ISSUE TITLE
[Docs] The "Getting Started" section does not clearly indicate if an adapter is optional or required

### ISSUE THREAD

**Issue by froschdesign** [schranz-search/schranz-search#155]
Adapters are introduced by the following sentence:

> The project provides adapters to different search engines. Choice the one which fits your needs best:

https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#installation

The section does not include the fact that an adapter is a requirement. But the following section ("Configure Engine") requires an adapter:

> It requires an instance of the Adapter which we did install before.

https://github.com/schranz-search/schranz-search/blob/0.1/docs/getting_started/index.rst#configure-engine

**Comment by alexander-schranz** [comment]
Thx for the feedback did change the sentence that it is written that `atleast one adapter is required` in #159. In the getting started nothing is in case optional as it only concentrate to get things started as fast as required.

**Comment by alexander-schranz** [comment]
@froschdesign build docs are available here currently: https://schranz-search.github.io/schranz-search/
