### ISSUE TITLE
[Docs] A diagram for the abstraction layer could be helpful

### ISSUE THREAD

**Issue by froschdesign** [schranz-search/schranz-search#158]
A diagram illustrating the abstraction layer from the application to SEAL, adapter and search engine could be helpful. This could also explain the adapters themselves.
Added to the "Getting Started" section.

**Comment by alexander-schranz** [comment]
@froschdesign Really thank you for the feedback and that you did take the time to have a look at this!

**Comment by froschdesign** [comment]
Do you prefer a simple image or a Mermaid graph?

**Comment by alexander-schranz** [comment]
Think `mermaid` is always good to quickly edit things and an image is easy to generate out of it if we want to move things, but not sure if there is a sphinx plugin already for it 🤔

**Comment by froschdesign** [comment]
> …but not sure if there is a sphinx plugin already for it

https://sphinxcontrib-mermaid-demo.readthedocs.io/en/latest/

**Comment by alexander-schranz** [comment]
I added a diagram here to the first site of the docs. https://schranz-search.github.io/schranz-search/ what do you think?
