### ISSUE TITLE
[Mezzio] Integration Module

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#164]
It would be nice to support also Mezzio framework. Currently I did only have a short look how this could be integrated, and failed to understand how I can create services based on configuration. I know how to get config inside a factory but not how the config can control that one or multipl services are created.

Every service seems require a factory be configured at the time where we don't have the config (e.g.: https://github.com/schranz-templating/templating/blob/eb28f45eabec42a5738b999030ab8e9e049d4fd7/src/Integration/Mezzio/Latte/ConfigProvider.php#L31-L35). So we can do `Engine::class -> MezzioEngineFactory::class` but not sure how to handle this if we want to create based on configuration multiple instances of the `Engine` like we are doing it here in the other frameworks:

 - https://github.com/schranz-search/schranz-search/blob/b5fe051db7618bee9a6ea27674467d5e41f76646/integrations/laravel/src/SearchProvider.php#L79
 - https://github.com/schranz-search/schranz-search/blob/b5fe051db7618bee9a6ea27674467d5e41f76646/integrations/spiral/src/Bootloader/SearchBootloader.php#L84
 - https://github.com/schranz-search/schranz-search/blob/b5fe051db7618bee9a6ea27674467d5e41f76646/integrations/symfony/src/SearchBundle.php#L70

I also did have a look at the `Doctrine` integration but not understand how it was handled there that multipl instances of entity manager can exist 🤔 .

**Comment by froschdesign** [comment]
@alexander-schranz 
A config provider class is good start. There can we do the same like in the boot loader for Spiral.

Here is a short example:

```php
use Psr\Container\ContainerInterface;
use Schranz\Search\SEAL\Adapter\Meilisearch\MeilisearchAdapterFactory;
// …

final class ConfigProvider
{
    public function __invoke(): array
    {
        return [
            'dependencies' => $this->getDependencies(),
        ];
    }

    public function getDependencies(): array
    {
        $dependencies = [
            'factories' => [
                // …
            ],
        ];

        if (\class_exists(MeilisearchAdapterFactory::class)) {
            $dependencies['factories'] += [
                'schranz_search.engine.meilisearch'        => EngineAbstractFactory::class,
                'schranz_search.adapter.meilisearch'       => AdapterAbstractFactory::class,
                'schranz_search.schema.meilisearch'        => SchemaAbstractFactory::class,
                'schranz_search.schema_loader.meilisearch' => SchemaLoaderAbstractFactory::class,
                MeilisearchAdapterFactory::class           => static function (
                    ContainerInterface $container
                ) {
                    return new MeilisearchAdapterFactory($container);
                },
            ];
        }

        if (\class_exists(OpensearchAdapterFactory::class)) {
            $dependencies['factories'] += [
                'schranz_search.engine.opensearch'        => EngineAbstractFactory::class,
                'schranz_search.adapter.opensearch'       => AdapterAbstractFactory::class,
                'schranz_search.schema.opensearch'        => SchemaAbstractFactory::class,
                'schranz_search.schema_loader.opensearch' => SchemaLoaderAbstractFactory::class,
                OpensearchAdapterFactory::class           => static function (
                    ContainerInterface $container
                ) {
                    return new OpensearchAdapterFactory($container);
                },
            ];
        }

        // …

        return $dependencies;
    }
}
```


For the class "Engine", an abstract class can be used that creates an instance based on the requested service name.

Something like this one:

```php
final class EngineAbstractFactory
{
    public function __invoke(
        ContainerInterface $container,
        string $requestedName,
        ?array $options = null
    ) {
        /**
         * Example:
         * $requestedName = 'schranz_search.engine.meilisearch';
         */
        $name = substr($requestedName, strrpos($requestedName, '.') + 1);

        $adapterServiceId = 'schranz_search.adapter.' . $name;
        $schemaId         = 'schranz_search.schema.' . $name;

        /** @var AdapterInterface $adapter */
        $adapter = $container->get($adapterServiceId);
        /** @var Schema $schema */
        $schema = $container->get($schemaId);

        return new Engine($adapter, $schema);
    }
}
```

For the adapters:

```php
final class AdapterAbstractFactory
{
    private ?array $config = null;

    public function __invoke(
        ContainerInterface $container,
        string $requestedName,
        ?array $options = null
    ) {
        $engines = $this->getConfig($container);
        
        $name = substr($requestedName, strrpos($requestedName, '.') + 1);
        $engineConfig = $engines[$name] ?? [];

        // …
    }

    private function getConfig(ContainerInterface $container): array
    {
        if ($this->config !== null) {
            return $this->config;
        }

        if (! $container->has('config')) {
            $this->config = [];

            return $this->config;
        }

        $config       = $container->get('config');
        $this->config = $config['engines'] ?? [];

        return $this->config;
    }
}
```
_The examples are not complete and also only a first idea._

**Comment by alexander-schranz** [comment]
Thx for your fast and detailed response.

I hope I dont sound dumb 🙈 . What I'm not understanding how we get the config inside `getDependencies` that we can loop over the configured `engines`, and there use the EngineFactory multiple times based on the configuration not a class_exists. As the configuration allows that we have 2 different Engines that can communicate with 2 different instances of the same search engine, so it is not that only can exist one instance of an engine with an adapter. Example something like this can also be configured:

```php
[
    'schranz_search' => [
        'engines' => [
            'meilisearch_1' => [
                'adapter' => 'meilisearch://127.0.0.1:7700',
            ],
            'meilisearch_2' => [
                'adapter' => 'meilisearch://127.0.0.1:7701',
            ],
        ],
    ],
];
```

As I'm understanding a `Factory` can only return one instance of a service, so we can not create a factory which returns or set multiple instances of a service? And inside the `$this->getDependencies` method the config is not available, that we can create there multiple instances?

**Comment by froschdesign** [comment]
@alexander-schranz 
> As the configuration allows that we have 2 different Engines that can communicate with 2 different instances of the same search engine…

Okay, that changes the whole thing and so this approach doesn't work that way.

---

Another idea is to create a separate dependency container (PSR-11) that manages all services of SEAL. This container can then be used in all integrations.
What do you think, could this work?

**Comment by alexander-schranz** [comment]
So Mezzio supports that there are multiple `containers`? How can I configure in Mezzio that I provide a whole custom psr-11 container?

What also is possible that we only provide `EngineRegistry` as a service and not in Mezzio to get a specific Engine they need to go over that service e.g.:

```php
$meiliSearch1 = $engineRegistry->getEngine('meilisearch_1');
$meiliSearch2 = $engineRegistry->getEngine('meilisearch_2');
```

we still could provide the `default` Engine over an own Factory via which does `$engineRegistry->getEngine('default');`.

**Comment by froschdesign** [comment]
> So Mezzio supports that there are multiple `containers`?

No, I mean this:

```php
$sealContainer = $applicationContainer->get(SealServiceContainer::class);
$meiliSearch1 = $sealContainer->get('meilisearch_1');
```

The `SealServiceContainer` can be prepared independently of the framework and then registered.
laminas-servicemanager has the [concept of plugin managers](https://docs.laminas.dev/laminas-servicemanager/plugin-managers/), but for SEAL I would take a simple PSR-11 container.

**Comment by froschdesign** [comment]
_I'm looking into another idea that matches your desired configuration…_

**Comment by alexander-schranz** [comment]
> The `SealServiceContainer` can be prepared independently of the framework and then registered ...

That could work and probably would also fix my current problem I stumble over when creating the integration over EngineRegistry which I tried out here as a prototype: https://github.com/schranz-search/schranz-search/pull/166/commits/3e67338b5acd5654ba6121b80809db53c5753e14 / #166 (untested). The problem is that the `Adapter` service is not exposed and so the ReadWrite and MultiAdapter can not access it.

**Comment by alexander-schranz** [comment]
@froschdesign another question to Mezzio, how can we provide console/cli commands to mezzio framework users?

**Comment by froschdesign** [comment]
@alexander-schranz 
Via laminas-cli, which is based on the Symfony Console, and I assume that you are already using this and therefore should not have any problems.
The explanation of how to register these commands can be found in the documentation of laminas-cli:

https://docs.laminas.dev/laminas-cli/intro/#register-command-in-an-application-with-configprovider-class-like-mezzio

**Comment by alexander-schranz** [comment]
Thank you, going over an own Container did work like expected and in #166 the Read-Write and Multi Adapter is now also working.

Another questions, I want the test the Functional Tests for ExampleControllers inside the example Mezzio Skeleton usage. I could not find official documentation how to create such Functional Controller Tests. Does there some kind of abstract FunctionalTestCase exist which I can use/extend from?

**Comment by alexander-schranz** [comment]
Thank you really for your help.
The first integration of the search abstraction into mezzio is merged 🎉 :

 - https://github.com/schranz-search/mezzio-module
 - https://packagist.org/packages/schranz-search/mezzio-module
 - https://schranz-search.github.io/schranz-search/getting_started/index.html

**Comment by froschdesign** [comment]
@alexander-schranz 
> Another questions, I want the test the Functional Tests for ExampleControllers inside the example Mezzio Skeleton usage. I could not find official documentation how to create such Functional Controller Tests. Does there some kind of abstract FunctionalTestCase exist which I can use/extend from?

The recommended way is a request handler and not a controller. (But you can [handle multiple routes in a single class](https://docs.mezzio.dev/mezzio/v2/cookbook/using-routed-middleware-class-as-controller/#handling-multiple-routes-in-a-single-class))

You can use the service container in tests via:

```php
public function testHandlerShouldDoSomething(): void
{
    $this->container = require '/path/to/config/container.php';

    // Create request, response, handler, …
}
```

Or you can use mezzio-test:
```php
protected function setUp(): void
{
    $this->mezzioApp = new MezzioTestEnvironment();
}

public function testHandlerShouldDoSomething(): void
{
    $this->mezzioApp->dispatch('…');
}
```

https://github.com/trinet-at/mezzio-test

I think mezzio-test is what you are looking for and what will help you here.

**Comment by alexander-schranz** [comment]
Thx for the quick response. Yeah it are `Handlers`, the `require` `container.php` is then fine in that case to avoid additional dependencies, I did use the same mechanism as in the `index.php` to create my FunctionalTestCase https://github.com/schranz-search/schranz-search/blob/09d5cc789116393fbea5a709a5ff497dfe0224bb/.examples/mezzio/test/AppTest/FunctionalTestCase.php#L19 :) 

The test did feel fine for this case: https://github.com/schranz-search/schranz-search/blob/09d5cc789116393fbea5a709a5ff497dfe0224bb/.examples/mezzio/test/AppTest/Handler/SearchHandlerTest.php#L27-L28

Even the Command did work also fine: https://github.com/schranz-search/schranz-search/blob/0.1/.examples/mezzio/test/AppTest/Command/CommandTest.php
