### ISSUE TITLE
[Yii] Integration Module

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#165]
As requested twitter it would also be good to have an integration into the Yii Ecosystem. Like for [Mezzio](https://github.com/schranz-search/schranz-search/issues/164) I think the most difficult part could be to create multiple instances of `Engine` like we are doing here in the other frameworks based on configuration:

 - https://github.com/schranz-search/schranz-search/blob/b5fe051db7618bee9a6ea27674467d5e41f76646/integrations/laravel/src/SearchProvider.php#L79
 - https://github.com/schranz-search/schranz-search/blob/b5fe051db7618bee9a6ea27674467d5e41f76646/integrations/spiral/src/Bootloader/SearchBootloader.php#L84
 - https://github.com/schranz-search/schranz-search/blob/b5fe051db7618bee9a6ea27674467d5e41f76646/integrations/symfony/src/SearchBundle.php#L70
 
Based on the following configuration two instances of engine with a seperate instance of adapter should be used:

```php
[
    'schranz_search' => [
        'engines' => [
            'meilisearch_1' => [
                'adapter' => 'meilisearch://127.0.0.1:7700',
            ],
            'meilisearch_2' => [
                'adapter' => 'meilisearch://127.0.0.1:7701',
            ],
        ],
    ],
];
```

**Comment by samdark** [comment]
There are two major versions of Yii currently active:

- Yii2 — likely a wrapper will be needed to use it conveniently. Also, it has its own search engine support on top of ActiveRecord: https://github.com/yiisoft/yii2-sphinx, https://github.com/yiisoft/yii2-elasticsearch
- Yii3 — it could be a good idea to make an integration package providing configs like https://github.com/yiisoft/cache-memcached/tree/master/config. It is like Symfony Flex recipes but a bit different. See https://github.com/yiisoft/config

**Comment by alexander-schranz** [comment]
@samdark Thx for your help. Another question what is the recommended to create CLI Commands?

Update looks like `yiisoft/yii-console` is shipped with the skeleton will go with that one.

**Comment by alexander-schranz** [comment]
Thank you really for your help.
The first integration of the search abstraction into yii is merged 🎉 :

 - https://github.com/schranz-search/yii-module
 - https://packagist.org/packages/schranz-search/yii-module
 - https://schranz-search.github.io/schranz-search/getting_started/index.html

**Comment by alexander-schranz** [comment]
@samdark currently it looks like the yii integration test is failing because of some upstream changes in the `yiisoft/yii-middleware`. Do you know how this can be fixed?

<img width="1255" alt="Bildschirmfoto 2023-05-09 um 00 56 36" src="https://user-images.githubusercontent.com/1698337/236955041-51ad8fa0-db68-4e55-95f0-5a013ed1b661.png">

**Comment by vjik** [comment]
Recently method in `Locale` middleware is renamed. Change `withEnableSaveLocale()` to `withSaveLocale()`

**Comment by alexander-schranz** [comment]
So the skeleton need to be udpated here: https://github.com/schranz-search/schranz-search/blob/57d2ab56229f31cb6116ec11f717bdbcdbed8605/.examples/yii/config/web/di/application.php#L26

Is this correct?

**Comment by samdark** [comment]
Yes.

**Comment by alexander-schranz** [comment]
Getting another error then 🤔 :

<img width="1669" alt="Bildschirmfoto 2023-05-10 um 00 21 55" src="https://github.com/schranz-search/schranz-search/assets/1698337/d66fbfea-80de-4e1a-b2eb-513e0af09a7b">

Think it has todo with this line: https://github.com/yiisoft/app/blob/e820a46f00d119a55a8029d734bc61770e2cfcef/config/common/di/router.php#L21

But not sure how to fix it even when I remove `/_language` here and replace with `/` it still appears.

**Comment by vjik** [comment]
@alexander-schranz See https://github.com/yiisoft/app/pull/289

Need adapt code to last changes in `Locale` middleware from `yiisoft/yii-middleware` package.

**Comment by alexander-schranz** [comment]
Thx for the support here 👍
