### ISSUE TITLE
[Core] Bulk Action on Connection and Engine

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#24]
It should be possible to provide Bulk Action on Connection and Engine.

```php
$engine->bulk(string $index, \Generator $saveDocuments, \Generator $deleteDocuments, bulkSize: 100);

// and

$indexer->bulk(Index $index, \Generator $saveDocuments, \Generator $deleteDocuments, bulkSize: 100);
```

Engine not supporting bulk action can fallback to basic save and delete methods.

The `documents` should be able to be aryor \Generator for performance.

A `BulkableIndexerInterface` should be added so the fallback to the save/delete can be part of the Engine and not every adapter itself need to implement it.

Bulk Action make maybe sense in case of:

Implementing of Reindex Providers #16

**Comment by alexander-schranz** [comment]
Maybe a `new Bulk($saveDocuents, $deleteDocuments, size: 10)` would make sense. In that case `saveDocuments` and `deleteDocuments` could be `\Generators` and the one calling the `Bulk` don't need to keep Bulk sizing and calling Bulk method multple times in mind.

**Comment by zajca** [comment]
I was just playing with loupe adapter and without batch support I was indexing ~5k recors about 35minutes, so I've implemented own reindexing and with 100 batch it did take around 30s. I guess performance will suffer on every adapter when importing more documents, so batch API is must.
I like example of the API you have provided btw. Not sure how many backend support delete and update/create in same batch but I guess that it make sense you do want both operation on dataset.

**Comment by alexander-schranz** [comment]
@zajca thx for giving SEAL a try and give feedback here. For the adapters not supporting batch or have seperate APIs for update/create and batch I'm planning to fallback to the normal APIs. So they may not have performance improvement but the API from outside for all adapters will be the same and so people using SEAL don't need create different code depending on the Adapters.

**Comment by alexander-schranz** [comment]
this is in progress: https://github.com/schranz-search/schranz-search/pull/430
