### ISSUE TITLE
[Loupe] please add support for version 0.5.0

### ISSUE THREAD

**Issue by MDevster** [schranz-search/schranz-search#268]

**Comment by alexander-schranz** [comment]
Thx for the issue @MDevster do you want to give it a try? If there are no bc breaks it mostly jusr update composer.json.

**Comment by alexander-schranz** [comment]
Hello @MDevster, do you want to work on this or not?

**Comment by alexander-schranz** [comment]
Loupe 0.5 is WIP: https://github.com/schranz-search/schranz-search/pull/335
