### ISSUE TITLE
[Symfony] please add support for version ^5.4

### ISSUE THREAD

**Issue by MDevster** [schranz-search/schranz-search#269]

**Comment by alexander-schranz** [comment]
Support for Symfony 5.4 is not planned. The integration bundles are build on top of the `AbstractBundle` class of Symfony 6.1: https://symfony.com/blog/new-in-symfony-6-1-simpler-bundle-extension-and-configuration

I'm not planning to go back old Configuration, Extension, Bundle class structure.

Upgrading from 5.4 to 6.1 should normally be no problem I can recommend you https://github.com/rectorphp/rector-symfony. The only part you need to have a look at is the new security system but that is already available on 5.4 which you could tackle first in your project.

**Comment by MDevster** [comment]
Thanks for the explanation, I was planning to use SEAL as a replacement for the default search engine in Contao 4.13 since the version still has LTS until February 2025
https://github.com/contao/contao/blob/4.13/composer.json#L97

**Comment by alexander-schranz** [comment]
Adding a new search would I think be better on a newer version like Contao 5?
Contao 5 whould be supporting Symfony 6.3 and think Contao 5.3 LTS is coming next year. At end of November the new Symfony 6.4 will be released which would be the new LTS of Symfony. Wouldn't that be a better fit for a adding a new search, then targeting old version which mostly old projects will not change there search?
