### ISSUE TITLE
[Core] Add support for Nested Conditions Filters via AndCondition and OrCondition

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#317]
It would be great if we could also possibility to have complex filters which are combined via `OrCondition` and also have there again nested `AndCondition` inside.

The condition signature could looke like this:

```php
class OrCondition {
    public readonly array $conditions;
    
    public function __construct(...$conditions)
    {
        $this->conditions = $conditions;
    }
}

class AndCondition {
    public readonly array $conditions;
    
    public function __construct(...$conditions)
    {
        $this->conditions = $conditions;
    }
}
```

The queries in the specific `...Searcher` classes will get more complex. We would require to add some `Recursive functionality` and before implement such feature we require a research if this can even be achieved by all currently supported search engines.

**Comment by ToshY** [comment]
> ...research if this can even be achieved by all currently supported search engines

Done a quick search:

* algolia - [yes](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/combining-boolean-operators/)
* elasticsearch - ?
* opensearch - ?
* loupe - [yes](https://github.com/loupe-php/loupe/blob/main/docs/searching.md#filter)
* meilisearch - [yes](https://www.meilisearch.com/docs/learn/fine_tuning_results/filtering#filter-expressions)
* redisearch - [yes](https://redis.io/docs/interact/search-and-query/query/combined/)
* solr - [yes](https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-BooleanOperatorsSupportedbytheStandardQueryParser)
* typesense - ?

I'm not sure about elasticsearch, opensearch and typesense.

**Comment by alexander-schranz** [comment]
@ToshY thx for the research:

The others seems also support it:

 - elasticsearch/opensearch can use the Boolquery: https://www.elastic.co/guide/en/elasticsearch/reference/8.11/query-dsl-bool-query.html#score-bool-filter
    - AND -> `bool:must`
    - OR -> `bool:should`
    - Nesting -> `nested bool queries`
 - typesense: https://github.com/typesense/typesense/issues/281
    - AND -> `&&`
    - OR -> `||`
    - Nesting -> `()`

**Comment by alexander-schranz** [comment]
implemented in #317

**Comment by ToshY** [comment]
@alexander-schranz Guess you meant implemented in #433 🙂 

Cool to see this implemented 👍 Will the docs also be updated with some examples on how to use these new conditions?

**Comment by alexander-schranz** [comment]
@ToshY Thanks.

Added examples for the two new conditions here: https://github.com/schranz-search/schranz-search/pull/441

Please let me know if that docs is clear enough.

**Comment by ToshY** [comment]
@alexander-schranz 

The examples are clear. 

While I'm not a native English speaker, I think the phrasing at "AndCondition" section (see [PR comment](https://github.com/schranz-search/schranz-search/pull/441/files#r1795870918)) could be a bit improved grammatically, but that's just me being nitpicky 🤐
