### ISSUE TITLE
[Core] Parameter `index_name_prefix` ignored when using one schema file per index

### ISSUE THREAD

**Issue by dhirtzbruch** [schranz-search/schranz-search#320]
### Discussed in https://github.com/schranz-search/schranz-search/discussions/319

<div type='discussions-op-text'>

<sup>Originally posted by **dhirtzbruch** December 15, 2023</sup>
Can someone tell me what the `index_name_prefix` in the SymfonyBundle is used for? By the parameter name I thought it should be possible to add a prefix to any index used when creating indexes as well as when querying the data - but I could not get that to work.

Use case would be using the same ElasticSearch cluster for staging / prod environments, and just automatically having the prefix added through the bundle configuration.</div>

<div type='discussions-op-text'>

<sup>Answer by **alexander-schranz**</sup>
It was created for that usecase, specially running tests in another env with a prefix. But if I look there is currently the prefix only used when there are multiple files. So think there is a bug here:
</div>

**Comment by dhirtzbruch** [comment]
Should be all done

**Comment by alexander-schranz** [comment]
fixed via #321
