### ISSUE TITLE
[Core] Add method `getDocumentIdentifierFieldName()`

### ISSUE THREAD

**Issue by ker0x** [schranz-search/schranz-search#352]
Hello @alexander-schranz and thanks for this package.

It would be nice if the `EngineInterface` had a `getDocumentIdentifierFieldName()` method, which would return the name of the identifier used on the index.

The method signature would looks like this:

```php
/**
  * @throws IndexNotFoundException
  */
public function getDocumentIdentifierFieldName(string $index): string;
```

It's similar to what doctrine does with entities and their metadata: https://github.com/doctrine/persistence/blob/3.2.x/src/Persistence/Mapping/ClassMetadata.php#L90

WDYT?

**Comment by ker0x** [comment]
Another possibility would be to have a `getIndexMetadata()` method that returns an `IndexMetadata` class with all relevant informations about the index (name, identifier field, definition etc...).

**Comment by alexander-schranz** [comment]
Thx for your idea, but the engine class is not responsible for providing such things, the Schema/Index is its own service. If you require it inject the Schema instance into your service and get the index from it and use the existing `getIdentifierField` method here: https://github.com/schranz-search/schranz-search/blob/b7fed9cdf3af9350b1bcf1a656026f6f0ebcfc32/packages/seal/src/Schema/Index.php#L58.

**Comment by alexander-schranz** [comment]
https://github.com/schranz-search/schranz-search/pull/366 will make possible to inject the `Schema` via Frameworks autowiring feature, and so should make it easier for your services requiring schema specific data:

```php
namespace App;

use Schranz\Search\SEAL\Schema\Schema;

class SomeAny {
    public function __construct(
        private EngineInterface $engine,
        private Schema $schema, // this is now by supported Frameworks autowired
    ) {}
  
    public function someMethod(): void {
        $this->schema->indexes['blog']->getIdentifierField()->name;
    }
}
```
