### ISSUE TITLE
[Core] Add condition `GeoDistanceCondition`

### ISSUE THREAD

**Issue by ker0x** [schranz-search/schranz-search#364]
I open this issue following my PR (#363) to introduce a new `GeoDistanceCondition` condition. According to my research, all search engines seem to support geographic search within a given radius.

- [Algolia](https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/)
- [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html)
- [Loupe](https://github.com/loupe-php/loupe/blob/main/docs/searching.md#geo-search)
- [Meilisearch](https://www.meilisearch.com/docs/learn/fine_tuning_results/geosearch)
- [OpenSearch](https://opensearch.org/docs/latest/query-dsl/geo-and-xy/index/)
- [RediSearch](https://redis.io/docs/interact/search-and-query/advanced-concepts/query_syntax/#geo-filters)
- [Solr](https://solr.apache.org/guide/6_6/spatial-search.html)
- [Typesense](https://typesense.org/docs/0.24.0/api/geosearch.html#searching-within-a-radius)

For the moment, I've only implemented it on `Meilisearch` and `Loupe`, which share a similar API.

**Comment by alexander-schranz** [comment]
Thx for the issue and the links to the different engines 👍

**Comment by ker0x** [comment]
Closing as completed in #363
