### ISSUE TITLE
[Core] Add condition `GeoBoundingBoxCondition`

### ISSUE THREAD

**Issue by ker0x** [schranz-search/schranz-search#365]
I open this issue following my PR (#420) to introduce a new `GeoBoundingBoxCondition` condition. According to my research, almost all search engines seem to support geographic search within a bounding box. Only Loupe does not implement this feature yet.

- [Algolia](https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/how-to/filter-results-inside-a-rectangle-area/)
- [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html)
- [Meilisearch](https://www.meilisearch.com/docs/learn/fine_tuning_results/geosearch#_geoboundingbox)
- [OpenSearch](https://opensearch.org/docs/latest/query-dsl/geo-and-xy/geo-bounding-box/)
- [RediSearch](https://redis.io/docs/interact/search-and-query/advanced-concepts/query_syntax/#geo-filters)
- [Solr](https://solr.apache.org/guide/6_6/spatial-search.html#SpatialSearch-Filteringbyanarbitraryrectangle)
- [Typesense](https://typesense.org/docs/0.24.0/api/geosearch.html#searching-within-a-geo-polygon)

For the moment, I've only implemented it on `Meilisearch`.

**Comment by alexander-schranz** [comment]
Thx for the issue and the links to the different engines 👍

**Comment by alexander-schranz** [comment]
Some research data not complete yet how different search engines do a bounding box query or polygon based queries:

| Search Engine | GeoBoundingBox Algorithm | Link
|---------------|--------------------------|-----------------------
| Meilisearch   | ↙️ Top Right -> Bottom Left | [Docs](https://www.meilisearch.com/docs/learn/filtering_and_sorting/geosearch#_geoboundingbox)
| Algolia |  ↘️ Top Left -> Bottom Right <br/> ↪️ Polygon | [Docs](https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/how-to/filter-results-inside-a-rectangle-area/)
| Elasticsearch |  ↘️ Top Left -> Bottom Right <br/> ↪️ Polygon | [Docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html)
| Opensearch    |  ↘️ Top Left -> Bottom Right <br/> ↪️ Polygon | [Docs](https://opensearch.org/docs/latest/query-dsl/geo-and-xy/geo-bounding-box/)
| Typesense     | ↪️ Polygon right handed (lat, lon, lat, ..) | [Docs](https://typesense.org/docs/27.0/api/geosearch.html#searching-within-a-radius)
| Solr | ↗️ Bottom Left -> Top Right <br/> ↪️ Polygon (lat lon, lat ...) (requires additional .jar JTS / Geo3d) | [Docs](https://solr.apache.org/guide/solr/latest/query-guide/spatial-search.html#geo3d-and-polygons-on-the-ellipsoid)
| Redisearch | ↪️ Polygon right handed?? | [Docs](https://redis.io/docs/latest/develop/interact/search-and-query/query/geo-spatial/)
| Loupe | ⚫ No support yet  | [Docs](https://github.com/loupe-php/loupe/blob/main/docs/searching.md#geo-search)

Meilisearch expected Top Right -> Bottom Left, while most others go on Top Left and Bottom Right. Polygon based queries are normally counter clockwise (right handed rule) but they seems in most cases just use the shortest distance.

Lot of documentation reference for polygon search also Well Known text representation of geometry https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

**Comment by alexander-schranz** [comment]
Interesting info MapBox uses Top Right (northEast) and Bottom Left (southWest):

https://docs.mapbox.com/help/glossary/bounding-box/

Same for Google maps uses:

https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLngBounds

It seems also why Meilisearch changed its behaviour to make things maybe easier in JS as you can then directly forward them to filter correctly: https://github.com/meilisearch/specifications/pull/223

**Comment by alexander-schranz** [comment]
moved the missing part (RediSearch) into own ticket: https://github.com/schranz-search/schranz-search/issues/422
