### ISSUE TITLE
[Core] Split Connection Read and Write processes into separate services

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#42]
Currently the connection is responsible to save, delete and even search documents. It maybe make sense to split this more up. Example [`laravel/scout`](https://laravel.com/docs/9.x/scout) uses the terms `Seeker` and `Indexer` to split read and write processes into seperate services.

The Schema should be keept in an own services as it make sense that SchemaManagement is divided from indixing.

This splitting would also make the ReadWrite Adapter simpler https://github.com/schranz-search/schranz-search/blob/bdf70065340d9f6d7873857bfd8ec6fd6ee8f297/packages/seal-read-write-adapter/ReadWriteAdapter.php#L26-L29 as it not longer requires a `ReadWriteConnection` instead the `ReadWriteAdapter` just return on `getReader/getSeeker` the read instance of the read adapter and `getWriter/getIndexer` the write instance of the write adapter.

@wachterjohannes what do you think?

**Comment by wachterjohannes** [comment]
@alexander-schranz makes totally sense in my opinion - although i dont like the term seeker :) but as it describes what it does i would go with it

**Comment by alexander-schranz** [comment]
Maybe best here would be to call it `Read(er)Interface` and `Write(r)Interface` which matches best the ReadWriteAdapter where this two services are used from different adapters. Names I did come up with:

 - A: ReadInterface / WriteInterface (AdapterInterface: getReader / getWriter)
 - B: ReaderInterface / WriterInterface (AdapterInterface: getReader / getWriter)
 - C: SeekerInterface / IndexerInterface (AdapterInterface: getSeeker / getIndexer)

@toflar what naming you would use here?

**Comment by Toflar** [comment]
I would use `Indexer` for sure.
For searching, that's usually `to query`. But there's no noun for that so a `Querier` or whatever does not make any sense. I'd go with `Searcher` probably.

**Comment by alexander-schranz** [comment]
`Searcher` / `Indexer` sounds good thx for your feedback.

**Comment by alexander-schranz** [comment]
All adapters migrated to the new interfaces.
