### ISSUE TITLE
Identifiers for meilisearch and probably others need to be checked

### ISSUE THREAD

**Issue by Toflar** [schranz-search/schranz-search#426]
If you use a document with the ID `foo.bar`, it will cause issues because meilisearch does not support `.` in identifiers: https://www.meilisearch.com/docs/learn/getting_started/primary_key#formatting-the-document-id

However, other search engines do. For compatibility, I guess the marshaller would need to normalize these identifiers.
What do you think?

**Comment by alexander-schranz** [comment]
The . is also object separetor for the internal flattenmarshaller or nested object conditions. I think we may shoud prevent that chars and only support a-z, A-Z and _ to support camel or snake case field names. Would that be a big problem in your case?

**Comment by Toflar** [comment]
No not at all. That's why I asked :) We should just make sure that the identifiers we allow work on all platforms so switching is easy :)

**Comment by alexander-schranz** [comment]
#427 forces field names with a-z, A-Z, 0-9, _ all fields need to start with `a-z`, `A-Z` currently.
