### ISSUE TITLE
Moving to a new namespace and package name

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#428]
The project did begin as a research project and so I quickly created a `schranz-search` and used the `Schranz\Search\SEAL\` namespace. This will be changed for 1.0 release. Currently different namespaces are in discussions. An upgrade via `RenameNamespaceRector` or via Search and Replace in your codebase should be easy.

What these also means is that we will may also move the name of the `composer` package. This sadly will loose our packagist statistic, but better early as later.

FYI: @ker0x, @toflar

CURRENT UPGRADE INSTRUCTIONS can be found in the old organisation: https://github.com/schranz-search/

**Comment by alexander-schranz** [comment]
In #458 we moved the project to the new organisation.

**Comment by jdreesen** [comment]
May I ask what CMS-IG stands for?

**Comment by alexander-schranz** [comment]
@jdreesen added a description to the organisation here: https://github.com/PHP-CMSIG
