### ISSUE TITLE
[Core] Add support for `NotInCondition` 

### ISSUE THREAD

**Issue by ToshY** [schranz-search/schranz-search#445]
**Suggestion**

The ability to check for multiple values using a `NOT IN` condition would be nice to have. The idea would be roughly be identical to the `NotEqualCondition` except the second argument allows an array (multiple values).

```php
<?php

use Schranz\Search\SEAL\Search\Condition;

$result = $this->engine->createSearchBuilder()
    ->addIndex('blog')
    ->addFilter(new Condition\NotInCondition('tags', ['UI','UX','Frontend']))
    ->getResult();
```

---

This probably would require research to check if all engines allow a kind of "IN".

* algolia - [`AND NOT` chaining](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/combining-boolean-operators/#example-scenarios) (unsure)
* elasticsearch - [`terms` with `must_not`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html)
* opensearch - [`terms` with `must_not`](https://opensearch.org/docs/latest/query-dsl/term/terms/)
* loupe - ?
* meilisearch - [`NOT IN`](https://www.meilisearch.com/docs/learn/filtering_and_sorting/filter_expression_reference#in)
* redisearch - [`|` chaining (negated); `-@x:(foo|bar)`](https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/query_syntax/#mapping-common-sql-predicates-to-redis-query-engine) (unsure)
* solr - ?
* typesense - ?

**Comment by alexander-schranz** [comment]
Thx for creating the issue.

At the end a `NotInCondition` is nothing else / a short cut of a combination of `NotEqualConditions` inside `AndCondition`. So we could always fallback to that, as AndCondition are implemented everywhere if there is no direct support for NOTIN. 

```php
new Condition\AndCondition(
    new Condition\NotEqualCondition('tags', 'UI'),
    new Condition\NotEqualCondition('tags', 'UX'),
    new Condition\NotEqualCondition('tags', 'Frontend'),
);
```

**Comment by alexander-schranz** [comment]
Let me know if you want to give it a try to contribute this feature. It should be very similar to: https://github.com/schranz-search/schranz-search/pull/447

**Comment by ToshY** [comment]
> Let me know if you want to give it a try to contribute this feature. It should be very similar to: #447

Oh nice that you've already implemented the `InCondition` at #444 . Looking at that PR, I can give it a try for this one.

**Comment by alexander-schranz** [comment]
@ToshY try what you can do. I can if you stuck with something help or finish it. Looking forward to have also this added.

**Comment by alexander-schranz** [comment]
Implemented in https://github.com/schranz-search/schranz-search/pull/448 :tada:
